/**
 * The at-rest credential encryption, at its two edges: it must refuse anything
 * it did not produce, and it must still read what the AES-256-CBC version
 * produced -- those values are live in production and cannot be re-encrypted
 * without the key and a running server.
 *
 * The AES fixtures are built here with `crypto` directly rather than imported
 * from anywhere, because the code that wrote them no longer exists. A fixture
 * generated by the module under test would only prove the module agrees with
 * itself.
 */
import crypto from "crypto";
import { decrypt, encrypt, encryptField, isLegacyCiphertext } from "../encryption";

const ENV_KEY = process.env.SETTINGS_ENCRYPTION_KEY as string;

/** Exactly what the previous implementation wrote: `ivHex:ciphertextHex`. */
function legacyEncrypt(text: string, key: Buffer): string {
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv("aes-256-cbc", key, iv);
    const encrypted = Buffer.concat([cipher.update(text, "utf8"), cipher.final()]);
    return `${iv.toString("hex")}:${encrypted.toString("hex")}`;
}

const SHA256_KEY = crypto.createHash("sha256").update(ENV_KEY).digest();
/** The pre-SHA-256 derivation: the first 32 bytes of the raw env var. */
const RAW32_KEY = Buffer.from(ENV_KEY.slice(0, 32));

describe("at-rest encryption", () => {
    it("round-trips, including unicode and a long value", () => {
        for (const value of ["hunter2", "sk-Ab3_x-9", "päßwörd 🎵 ключ", "k".repeat(4096)]) {
            expect(decrypt(encrypt(value))).toBe(value);
        }
    });

    it("never produces the same ciphertext twice for the same plaintext", () => {
        // A fresh nonce per encryption. Equal ciphertexts would mean equal
        // nonces, which for XChaCha20 is the one failure that silently
        // destroys confidentiality rather than throwing.
        const a = encrypt("the same secret");
        const b = encrypt("the same secret");
        expect(a).not.toBe(b);
        expect(decrypt(a)).toBe("the same secret");
        expect(decrypt(b)).toBe("the same secret");
    });

    it("throws when a single byte of the ciphertext is flipped", () => {
        // The property AES-256-CBC did not have. Under CBC this returned
        // corrupted plaintext or a padding error depending on where the flip
        // landed; a caller could not tell a modified credential from a valid one.
        const sealed = encrypt("sk-live-do-not-change-me");
        const blob = Buffer.from(sealed.slice("xc1.".length), "base64url");
        blob[blob.length - 5] ^= 0x01;
        const tampered = "xc1." + blob.toString("base64url");

        expect(tampered).not.toBe(sealed);
        expect(() => decrypt(tampered)).toThrow();
    });

    it("throws when the nonce is altered, not just the ciphertext body", () => {
        const sealed = encrypt("sk-live-do-not-change-me");
        const blob = Buffer.from(sealed.slice("xc1.".length), "base64url");
        blob[0] ^= 0xff;
        expect(() => decrypt("xc1." + blob.toString("base64url"))).toThrow();
    });

    it("throws on a truncated value rather than reading a short buffer", () => {
        const sealed = encrypt("sk-live-do-not-change-me");
        const blob = Buffer.from(sealed.slice("xc1.".length), "base64url");
        expect(() => decrypt("xc1." + blob.subarray(0, 20).toString("base64url"))).toThrow(
            /too short/
        );
        expect(() => decrypt("xc1." + blob.subarray(0, 30).toString("base64url"))).toThrow();
    });

    it("throws on plaintext, which it used to hand straight back", () => {
        // The fail-open hole this change closes: anything unrecognised was
        // returned to the caller as though it were the decrypted value, so
        // database write access alone was enough to inject a credential.
        for (const notCiphertext of [
            "sk-attacker-controlled-key",
            "https://evil.example/api",
            "not:hex:at:all",
            "xc1.",
            "xc1.!!!not-base64!!!",
        ]) {
            expect(() => decrypt(notCiphertext)).toThrow();
        }
    });

    it("still reads a value written by the old AES-256-CBC implementation", () => {
        const stored = legacyEncrypt("lidarr-api-key-from-production", SHA256_KEY);
        expect(isLegacyCiphertext(stored)).toBe(true);
        expect(decrypt(stored)).toBe("lidarr-api-key-from-production");
    });

    it("still reads an even older value, from before the key was SHA-256 normalized", () => {
        const stored = legacyEncrypt("pre-normalization-secret", RAW32_KEY);
        expect(decrypt(stored)).toBe("pre-normalization-secret");
    });

    it("throws on an AES-shaped value encrypted under someone else's key", () => {
        const stored = legacyEncrypt("not yours", crypto.randomBytes(32));
        // Not asserted to throw a SPECIFIC error: CBC has no MAC, so a wrong
        // key fails on padding, which is chance rather than detection. That is
        // the reason the format changed; here it is only required not to
        // succeed silently.
        let result: string | undefined;
        let threw = false;
        try {
            result = decrypt(stored);
        } catch {
            threw = true;
        }
        expect(threw || result !== "not yours").toBe(true);
    });

    it("treats empty as empty, at both ends", () => {
        expect(encrypt("")).toBe("");
        expect(decrypt("")).toBe("");
        expect(encryptField("")).toBeNull();
        expect(encryptField("   ")).toBeNull();
        expect(encryptField(null)).toBeNull();
        expect(encryptField(undefined)).toBeNull();
    });

    it("encryptField produces something decrypt accepts, and not the plaintext", () => {
        const stored = encryptField("audiobookshelf-token");
        expect(stored).not.toBeNull();
        expect(stored).not.toContain("audiobookshelf-token");
        expect(stored?.startsWith("xc1.")).toBe(true);
        expect(decrypt(stored as string)).toBe("audiobookshelf-token");
    });

    it("does not write the legacy format any more", () => {
        expect(isLegacyCiphertext(encrypt("anything"))).toBe(false);
    });
});
