-- Re-derive Artist.normalizedName so stored values match how they are queried.
--
-- Two functions named normalizeArtistName existed with different behaviour, on
-- opposite sides of this column: the one in services/artistIdentity.ts WRITES it
-- (via resolveArtist), while the one in utils/artistNormalization.ts was used to
-- QUERY it from ~20 call sites in spotifyImport and discoverWeekly. They
-- disagreed on the ligature fold, because only the writer folded characters that
-- carry no combining mark:
--
--   "MØ"          written "mo"           queried "mø"
--   "Kælan Mikla" written "kaelan mikla" queried "kælan mikla"
--   "Sløtface"    written "slotface"     queried "sløtface"
--
-- Any artist with such a character was therefore unfindable by Spotify import
-- matching and Discover Weekly seeding. The duplicate has been deleted and that
-- module now re-exports the single definition, but rows written by the previous
-- code still hold the unfolded form, so they are re-derived here.
--
-- The equivalence this relies on runs the other way round from how it reads:
-- the TypeScript folds the way unaccent() does, because src/services/pgTextRules.ts
-- is GENERATED by sweeping unaccent() (and [:alnum:], lower() and \s) over the
-- whole Basic Multilingual Plane in this Postgres image. So the two agree by
-- construction rather than by anyone keeping a hand-written table in step.
--
-- src/services/__tests__/pgIdentityParity.test.ts asserts it, against
-- expectations generated from the kima_* functions below -- 374 inputs covering
-- the cases that actually broke: ligatures, the Turkish dotted I, no-break
-- spaces, superscripts, Hangul, kana dakuten and the Unicode 14/15 additions.
-- (An earlier version of this comment claimed test coverage that did not exist:
-- the test it pointed at asserted three hardcoded literals and never executed
-- unaccent() at all.)

CREATE EXTENSION IF NOT EXISTS unaccent;

UPDATE "Artist"
SET "normalizedName" = regexp_replace(
        regexp_replace(lower(unaccent(trim(name))), '\s*&\s*', ' and ', 'g'),
        '\s+', ' ', 'g'
    )
WHERE "normalizedName" IS DISTINCT FROM regexp_replace(
        regexp_replace(lower(unaccent(trim(name))), '\s*&\s*', ' and ', 'g'),
        '\s+', ' ', 'g'
    );
