-- Columns with no reader anywhere in the codebase.
--
-- DownloadJob.triedReleases / releaseIndex were Soulseek release-cycling state:
-- the client walked a candidate list and remembered where it was. Nothing has
-- written or read them in a long time, they are absent from schema.prisma, and
-- grepping this tree finds no consumer. They go.
--
-- NOT DROPPED HERE, though upstream's version of this migration drops them:
-- SystemSettings.maxConcurrentDownloads, downloadRetryAttempts and
-- audioAnalyzerWorkers. Every reason upstream gives is true only on that line:
--
--   * maxConcurrentDownloads is called "a tear-out artefact" left beside
--     `concurrentDownloads` after a rename. This line never did that rename --
--     there is no concurrentDownloads column here, so maxConcurrentDownloads IS
--     the live key, and services/acquisition reads it.
--   * audioAnalyzerWorkers is called dead because "the vibe-engine replaced"
--     the audio-analyzer service. This line still ships the audio analyzer, and
--     the setting is read by the backend and rendered by two frontend files.
--   * downloadRetryAttempts has no reader today, but it is still declared in
--     schema.prisma, and Prisma fails EVERY SystemSettings query when the
--     schema names a column the database lacks.
--
-- Dropping them here took the whole server down at boot: the enrichment worker
-- could not read settings at all
-- ("The column SystemSettings.maxConcurrentDownloads does not exist"). That was
-- invisible to typecheck and to the test suite, because both halves agreed --
-- the schema kept the columns and only the SQL removed them. It surfaced the
-- first time the application was actually started against a migrated database.
ALTER TABLE "DownloadJob"    DROP COLUMN IF EXISTS "triedReleases";
ALTER TABLE "DownloadJob"    DROP COLUMN IF EXISTS "releaseIndex";
